require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
# used for automatic bumping
flipperkit_version = '0.151.1'

target 'bdovore' do
  config = use_native_modules!
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )


  target 'bdovoreTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper' => flipperkit_version, 'Flipper-Folly' => '2.6.10', 'Flipper-DoubleConversion' => '3.2.0', 'Flipper-Glog' => '0.5.0.3', 'Flipper-PeerTalk' => '0.0.4', 'OpenSSL-Universal' => '1.1.1100' })


  post_install do |installer|
    
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
		 config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
		end
	end
    flipper_post_install(installer)
     react_native_post_install(installer)
     
  end
end

  